export const APP = {
    INITIALIZED_APP: 'INITIALIZED_APP',
    SET_ERROR_MESSAGES: 'SET_ERROR_MESSAGES',
    INITIALIZED_SUCCESS: 'INITIALIZED_SUCCESS',
};

export const AUTH = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_USER_DATA: 'SET_USER_DATA',
    GET_AUTH_USER_DATA: 'GET_AUTH_USER_DATA',
};

export const USERS = {
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_USERS: 'SET_USERS',
    ALL_USERS: 'ALL_USERS',
    USER_REMOVE: 'USER_REMOVE',
    REQUEST_USERS: 'REQUEST_USERS',
    SET_ALL_USERS: 'SET_ALL_USERS',
    FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
    UNFOLLOW_SUCCESS: 'UNFOLLOW_SUCCESS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_FOLLOWED_USERS: 'SET_FOLLOWED_USERS',
    TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
    SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',
    TOGGLE_FOLLOWING_PROGRESS: 'TOGGLE_FOLLOWING_PROGRESS',
};

export const PROFILE = {
    USER_ID: 'USER_ID',
    ADD_POST: 'ADD_POST',
    SET_LIKE: 'SET_LIKE',
    GET_STATUS: 'GET_STATUS',
    SET_STATUS: 'SET_STATUS',
    SAVE_PHOTO: 'SAVE_PHOTO',
    REMOVE_POST: 'REMOVE_POST',
    UPDATE_DATA: 'UPDATE_DATA',
    UPDATE_STATUS: 'UPDATE_STATUS',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_PHOTO_SUCCESS: 'SET_PHOTO_SUCCESS',
};

export const MESSAGE = {
    SET_MARK: 'SET_MARK',
    GET_DIALOG: 'GET_DIALOG',
    START_DIALOG: 'START_DIALOG',
};
